### ISSUE TITLE
[ui-v2] Add automation tab to Dashboard

### ISSUE THREAD

**Issue by Srile** [zestymarket/ui-v2#39]
Users need to be able to configure the automation tools in dashboard tab. Here, they will be able to set the specific settings that the bot will auto-approve:

1) Automatic withdrawal of funds
2) Automatic approval of specific campaigns (Search dropdown that displays names)
3) Automatic Bidding settings (to be specified by @JSeam2)

**Comment by JSeam2** [comment]
addressed in #116
