### ISSUE TITLE
[ui-v2] Can't delete items in cart

### ISSUE THREAD

**Issue by Srile** [zestymarket/ui-v2#68]
I should be able to delete items off of the cart by pressing an `x` next to the item on the cart. (It should appear on hover on desktop and be always there on mobile)

Recommendation: `x` could be underneath the id of the item.

![image](https://user-images.githubusercontent.com/1471367/178147005-2867ccfa-9705-4dde-a0f0-4f9df4fc0be9.png)

**Comment by Komitaji** [comment]
This is not a bug rather a feature because the X in cart preview was never in the designs. But it's useful to have and I'll get started on this.
